### ISSUE TITLE
Bare metal clusters?

### ISSUE THREAD

**Issue by aemadrid** [getkuby/kuby-core#1]
Have you thought what it would take to make this work for bare metal clusters? I have a couple of k3s clusters running in VPSs and kuby sounds like a great tool for managing my apps.

**Comment by aemadrid** [comment]
In other words, could we make this work with just kubectl access?

**Comment by camertron** [comment]
Hey @aemadrid,

Hmm, that's a great question. It would probably be a good idea to create a generic "bare metal" provider you could configure with the path to your kubeconfig. In my experience though there are usually small little differences between providers that require tiny tweaks to certain k8s resources. For example, [here's a change](https://github.com/getkuby/kuby-digitalocean/blob/b1468b00bccb3679261b8ba067d4af6be7131371/lib/kuby/digitalocean/provider.rb#L51) I had to make to the ingress service for the DigitalOcean provider to get ingresses to work. I'm not that familiar with k3s, so I don't know if there are any such tweaks necessary. If so, then it's probably better to create a k3s-specific provider. What do you think?

**Comment by aemadrid** [comment]
k3s is a CNCF standard distro that uses very little resources. I guess if we could build a bare (e.g. kubectl) provider that would be a great start for a lot of people. then if we need to we could add hooks to configure each step needed. I'm not minimizing the complexity though. k8s is a very big beast that keeps on growing in size and complexity. I'm just hoping that kuby could provide a golden path for most people that just need to get things deployed.

**Comment by camertron** [comment]
Ok sounds like a great idea. Do you have time to submit a PR?

**Comment by aemadrid** [comment]
I'm reading through the code still but I'll give it a try. still not sure how all pieces fit here.

**Comment by camertron** [comment]
Yeah I understand, there are a lot of moving parts. Happy to hop on a call if you'd like.

**Comment by aemadrid** [comment]
Running through the quickstart guide right now. Let me get it going fully on an example app and then maybe we can get together on a chat.

**Comment by camertron** [comment]
Hey @aemadrid, I'm going to close this issue unless there's more to discuss. Let me know :)

**Comment by aemadrid** [comment]
Yes, go ahead. I think that #10 covers the needs for me. Thanks!
