### ISSUE TITLE
Create a basic "bare metal" provider

### ISSUE THREAD

**Issue by camertron** [getkuby/kuby-core#10]
Right now, the Kuby ecosystem supports a number of hosting providers like DigitalOcean, Linode, etc, but there's no way currently to deploy to a "bare metal" cluster, i.e. one you or your company manages. 

It would be great to have a generic provider that stubs out all the necessary methods. I think the only ones you will need to worry about are `kubeconfig_path` and `storage_class_name`. The user would configure the provider with the path to their kubeconfig (by default stored in ~/.kube/config), the storage class name (default could be "standard") and... that's basically it.

Inspired by issue #1.

**Comment by camertron** [comment]
A bare metal provider has been shipped with v0.12.0 🎉

**Comment by aemadrid** [comment]
Great!
