### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by webmatze** [getkuby/kuby-core#107]
The current Gemfile references a branch (initialize_void) for the parlour gem, that does not exist.

```ruby
gem 'parlour', github: 'camertron/parlour', branch: 'initialize_void' # '~> 7.0'
```

So Bundler fails with the following error message:

```bash
bundle
Fetching https://github.com/camertron/parlour.git
fatal: Benötigte einen einzelnen Commit
Git error: command `git rev-parse --verify initialize_void` in directory
/Users/mathiaskarstaedt/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/cache/bundler/git/parlour-2683f6fd0ad15802e284646268b7eb7ed717ab35 has failed.
Revision initialize_void does not exist in the repository https://github.com/camertron/parlour.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory
'/Users/mathiaskarstaedt/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/cache/bundler/git/parlour-2683f6fd0ad15802e284646268b7eb7ed717ab35'
```

After changing it back to '~> 7.0' which installs `parlour v7.0.0` it seems to be working.

```ruby
gem 'parlour', '~> 7.0'
```

Was there a reason behind the change?

**Comment by camertron** [comment]
This is a mistake on my part. The PR associated with the `initialize_void` branch was merged and the branch deleted. I think we should bump parlour to v8.0.0.

**Comment by camertron** [comment]
Done in https://github.com/getkuby/kuby-core/commit/610105d04a5e8620411953c9fe767eb418632731
