### ISSUE TITLE
[Feature Request] Add support for hetzner cloud 

### ISSUE THREAD

**Issue by kirantpatil** [getkuby/kuby-core#108]
Hi,

Please add support for https://www.hetzner.com/cloud ?

Thanks.

**Comment by camertron** [comment]
Hey @kirantpatil, thanks for your interest in Kuby. I don't believe Hetzner offers managed Kubernetes, is that correct? Of course you could create your own cluster and run it on their infrastructure, in which case you'd likely want to use the [bare metal provider](https://github.com/getkuby/kuby-core/blob/master/lib/kuby/kubernetes/bare_metal_provider.rb) and point it at your .kubeconfig.
