### ISSUE TITLE
Mutiple hostnames?

### ISSUE THREAD

**Issue by NikoDyring** [getkuby/kuby-core#112]
Hi! 👋🏻 

Is there a way to assign multiple hostnames in the Kubernetes config in `kuby.rb`? 🤔 

```ruby
  add_plugin :rails_app do
    hostname 'whatever.mydomain.com'
  end
```
How do I add more hostnames? 🤔 I can do it manually in my ingress config, but I'd love to have it in my application instead.

**Comment by camertron** [comment]
Hey @NikoDyring, great question 😄 Unfortunately there's not a super easy way to configure multiple hostnames at the moment. It shouldn't be too difficult to add to the framework if you're up for submitting a PR. If you have access to edit the DNS records for the domain, an "ALIAS" record might also work in the meantime.

**Comment by NikoDyring** [comment]
> Hey @NikoDyring, great question smile Unfortunately there's not a super easy way to configure multiple hostnames at the moment. It shouldn't be too difficult to add to the framework if you're up for submitting a PR. If you have access to edit the DNS records for the domain, an "ALIAS" record might also work in the meantime.

I've set it up in Kubernetes, and also at my domain, so it works without the multiple hostnames in kuby. I'd just prefer it was a feature :D Might look into it, in the future. Thanks for the quick answer!
