### ISSUE TITLE
Feature Request: support for Google Cloud - GKE as a provider

### ISSUE THREAD

**Issue by TylerSustare** [getkuby/kuby-core#129]
### Why do you think Kuby is a good solution?

Since GCP has a managed Kubernetes service like the current Kuby providers, I assume this is possible with Kuby.

These could be helpful links to start investigating: 
* [GKE Rest API documentation](https://cloud.google.com/kubernetes-engine/docs/reference/rest)
* [Ruby cloud client libraries](https://cloud.google.com/ruby/docs/reference)

### Context: Why is someone asking for this?

**tl;dr I like Google cloud. I would love to use Kuby on GCP via [GKE](https://cloud.google.com/kubernetes-engine).**

More context: I have an app with a small reach right now I'm looking to scale up. We made the MVP a Flutter app with a full Firebase backend. This worked great to find product market fit, but now we're now migrating to a proper back end. I'd like to use Kubernetes as my scaling solution. We're in it for the long haul with GCP because we started with Firebase. It would make it much easier for my team to move to a Kubernetes solution if it was in GCP. I'd like that Kubernetes solution to be managed by Kuby.

**Comment by camertron** [comment]
Hey @TylerSustare, thanks for the issue. I would love to see Kuby support GCP, it's been on my to-do list for ages. I'd be happy to take a swing at building a Kuby provider for it, but probably not for a few days at least. You might be able to put something together faster, and if so, I would gladly review the code and bring it into the getkuby GitHub org.

In the meantime, you may be able to get some mileage out of the [`BareMetalProvider`](lib/kuby/kubernetes/bare_metal_provider.rb), which allows you to "bring your own" kubeconfig. You could wire something together using the `gcloud` command to get the kubeconfig, then point the bare metal provider at it.

Eg. store the kubeconfig in /path/to/kubeconfig like so:

```bash
KUBECONFIG=/path/to/kubeconfig \
  gcloud container clusters get-credentials <cluster name> \
  --region <region> \
  --project <project>
```

Then point the provider at it:

```ruby
Kuby.define('my-app') do
  environment(:production) do
    kubernetes do
      provider :bare_metal do
        kubeconfig '/path/to/kubeconfig'
      end
    end
  end
end
```

You might also have to set the storage class by calling the `#storage_class("<storage class string>")` method (at the same level as the `#kubeconfig` method), but I would need to test it out.

**Comment by camertron** [comment]
Please see: https://github.com/getkuby/kuby-gke
