### ISSUE TITLE
getkuby.io is down

### ISSUE THREAD

**Issue by benjaminoakes** [getkuby/kuby-core#136]
First off, my apologies if this is not the right place to report this.

However, I thought you would want to know that https://getkuby.io/ cannot be reached.

I confirmed that this was not an issue specific to my network using https://downforeveryoneorjustme.com/getkuby.io?proto=https

I hope knowing this helps!

**Comment by camertron** [comment]
Hey @benjaminoakes, thanks for letting me know about this! I re-deployed the site and added a few IPv6 A records, and that appears to have helped? Can you confirm the site is available now?

**Comment by benjaminoakes** [comment]
>Hey @benjaminoakes, thanks for letting me know about this! 

Happy to have helped!

>I re-deployed the site and added a few IPv6 A records, and that appears to have helped? Can you confirm the site is available now?

Unfortunately, no.  The easiest way to check may be the second link I shared:  https://downforeveryoneorjustme.com/getkuby.io?proto=https

**Comment by benjaminoakes** [comment]
This is what I currently see at https://downforeveryoneorjustme.com/getkuby.io?proto=https:

![Screenshot 2023-10-25 05 50 02](https://github.com/getkuby/kuby-core/assets/5323/c3f83b96-52eb-4a72-82bb-da2fe3be1eff)

**Comment by camertron** [comment]
Thanks @benjaminoakes I finally got to the bottom of it. Turns out you have to have an active compute instance with Linode or they won't serve any of your DNS records 🤦 Thanks a lot Linode. I switched the NS records back to my registrar (Hover) and checked the DNS propagation with an online checker. Site should be working again.

**Comment by benjaminoakes** [comment]
Confirmed working! Glad we got to the bottom of this.
