### ISSUE TITLE
Is redis or memcached supported? 

### ISSUE THREAD

**Issue by jwald1** [getkuby/kuby-core#28]
Thanks for creating this amazing tool!

Does Kuby support Redis or Memcached? If so could you please provide some instructions how to add them to a project.

**Comment by camertron** [comment]
Hey @jwald1, thanks! Glad you're getting some use out of it :)

Redis and memcached are supported via [kubedb](https://kubedb.com/) and the corresponding [kuby-kube-db gem](https://github.com/getkuby/kuby-kube-db). Right now there's no nice or easy way to spin up new Redis or memcached instances, but you could definitely create a custom plugin and use the kuby-kube-db DSL to define the resources. Check out how kuby-sidekiq stands up a Redis [here](https://github.com/getkuby/kuby-sidekiq/blob/bb9f78ea4ae5ff8fd695a851daca9e483955e100/lib/kuby/sidekiq/plugin.rb#L134).

Here's a quick example:

```ruby
require 'kuby/kube-db'

class MyRedisPlugin < Kuby::Plugins::Plugin
  def resources
    [redis]
  end

  def redis
    context = self

    @redis ||= Kuby::KubeDB.redis do
      api_version 'kubedb.com/v1alpha1'

      metadata do
        name "my-awesome-redis"
        namespace context.kubernetes.namespace.metadata.name
      end

      spec do
        version '5.0.3-v1'
        storage_type 'Durable'

        storage do
          storage_class_name context.kubernetes.provider.storage_class_name
          access_modes ['ReadWriteOnce']

          resources do
            requests do
              add :storage, '1Gi'
            end
          end
        end
      end
    end
  end
end

Kuby.register_plugin(:my_redis, MyRedisPlugin)
```

and then in your kuby.rb:

```ruby
Kuby.define('my-app') do
  environment(:production) do
    kubernetes do
      add_plugin(:my_redis)
    end
  end
end
```

I've also filed an issue to make Redis and memcached into official Kuby plugins. We could also potentially detect what your Rails app is using for caching and automatically stand up the right instance.

**Comment by camertron** [comment]
I just published the [kuby-memcached](https://github.com/getkuby/kuby-memcached) and [kuby-redis](https://github.com/getkuby/kuby-redis) gems, plugins that can be used to stand up instances at will.
