### ISSUE TITLE
Kuby config path

### ISSUE THREAD

**Issue by aemadrid** [getkuby/kuby-core#3]
Looks like `Kuby.load!` expects to find `kuby.rb` in the root of the project instead of an initializer like the docs sugges (e.g. "Put the config into a Rails initializer, eg. config/initializers/kuby.rb."). Maybe it should not try to load if already defined by an initializer?

**Comment by camertron** [comment]
Ah sorry @aemadrid, that's another change I made recently in v0.6.0 🤦 `Kuby.load!` does indeed expect to find a `kuby.rb` in your root directory. I changed it to avoid needing to load the Rails environment for every rake task. I will update the docs right now.

**Comment by camertron** [comment]
As you can probably tell, Kuby is still very much a work in progress!

**Comment by aemadrid** [comment]
I was thinking that you could mark a flag if Kuby is already configured so you don't need to load it at all unless really needed.

**Comment by camertron** [comment]
Oh, actually Kuby will raise a `RuntimeError` if you try to call `Kuby.define` more than once. The `rescue` in the code snippet above was meant to handle the case when Kuby is in a separate `deploy` group in your gemfile, which, now that I think back, I stopped doing. So I think the initializer can simply be this now:

```ruby
require 'kuby'
Kuby.load!
```
