### ISSUE TITLE
image_url

### ISSUE THREAD

**Issue by traels** [getkuby/kuby-core#4]
> The image_url field is the full URL to your image, including the registry's domain.

Except for Docker Hub when it should not be there ... at least when pushing!?
Seems that it needs the full URL for deploy phase.

**Comment by camertron** [comment]
Hmm, both Docker and Kubernetes should know how to handle "bare" URLs. If I recall correctly, Kuby assumes `registry.hub.docker.com` if no hostname is provided. What specific issue did you run into during the deploy?

**Comment by traels** [comment]
My bad. Its in push that it failed. Maybe because I had used hub.docker.com.
Anyway, I think that guides per registry could be nice. If you are not home in the docker world it is a bit hard to know what repository URL to enter, since it is not always the one you see in your browser.

Sendt fra min iPad

**Comment by camertron** [comment]
That's a great idea, I'll add a better explanation to the docs :)

**Comment by camertron** [comment]
Added a better explanation to the README: https://github.com/getkuby/kuby-core/wiki/Quick-Start-Guide#choosing-a-docker-registry
