### ISSUE TITLE
Refresh kubeconfig if kuby config changes

### ISSUE THREAD

**Issue by camertron** [getkuby/kuby-core#40]
A number of the provider gems will attempt to use old kubeconfig files created for other clusters if the config parameters in kuby.rb change. One possible solution would be to use a hashed version of things like the cluster ID, access token, tenant ID, etc in the file path so any config changes will force a kubeconfig refresh. See: https://github.com/getkuby/kuby-digitalocean/issues/2

**Comment by pandwoter** [comment]
Hello, @camertron, I can work on this.
As I see now in kuby-core repo we have abstract method
```ruby
def kubeconfig_path
  raise NotImplementedError, "please define #{__method__} in #{self.class.name}"
end
```

and particular provider should implements it (example from digital ocean)

```ruby
def kubeconfig_path
  @kubeconfig_path ||= File.join(
    kubeconfig_dir, "#{environment.app_name.downcase}-kubeconfig.yaml"
  )
end
```

So should I implement fix for kuby-core (if so we anyways in need to rewrite this piece in every provider) or we can implement change for all providers in particular?

**Comment by camertron** [comment]
@pandwoter awesome, thank you for volunteering! I think it would be best to implement specific changes per provider gem, since each provider accepts a different set of configuration parameters. For example, Linode and DigitalOcean require a cluster ID and access token, but Azure requires a tenant ID, client ID, client secret, subscription ID, resource name, and resource group name.

**Comment by pandwoter** [comment]
Implemented for all providers

https://github.com/getkuby/kuby-digitalocean/pull/3
https://github.com/getkuby/kuby-eks/pull/3
https://github.com/getkuby/kuby-azure/pull/1

**Comment by camertron** [comment]
All merged and new versions released. Thank you!
