### ISSUE TITLE
Multiple apps in one cluster?

### ISSUE THREAD

**Issue by brandoncc** [getkuby/kuby-core#44]
Hi, thanks for this very promising project!

I am wondering if I can run my staging and production environments in the same cluster. If so, is there anything special I should know about how I need to configure the environments?

**Comment by camertron** [comment]
Hey @brandoncc. Yes, you should be able to run your staging and production environments on the same cluster. Kuby creates separate Kubernetes namespaces for each of your environments, eg. myapp-production and myapp-staging. Your Kuby config would look something like this:

```ruby
Kuby.define('MyApp') do
  environment(:production) do
    # production config
  end

  environment(:staging) do
    # staging config
  end
end
```

That said, it's considered a best-practice to stand up a separate cluster for each environment for a number of reasons, not the least of which is security. For example, your production cluster needs to be publicly available, while your staging cluster doesn't. If you run both on the same cluster, both have to be publicly available.

Either way, the kuby config snippet above should work :)

**Comment by brandoncc** [comment]
Interesting, I don't know how I would access a non publicly available staging... So much to learn. Thank you once again 💖

**Comment by camertron** [comment]
@brandoncc probably using a VPC with a VPN connection?

**Comment by brandoncc** [comment]
Ah, I didn't even know you could do that. I am used to staging apps on Heroku, paired with basic auth...thanks!
