### ISSUE TITLE
How do multiple nodes in a cluster work?

### ISSUE THREAD

**Issue by brandoncc** [getkuby/kuby-core#45]
Hi,

If I create a cluster with two nodes (for high availability), how does Kuby handle this?

If I have the sidekiq plugin, and therefore redis, do these get installed and run simultaneously on both nodes? What about the database? Does it get setup on both nodes and that might cause issues?

I don't know anything about kubernetes, so maybe these are things that should be obvious to me, but aren't.

Thank you for your time!

**Comment by brandoncc** [comment]
I saw the other open issue about assets after creating this issue. I am still curious about the db/sidekiq aspect though.

**Comment by camertron** [comment]
Hey @brandoncc, that's a good question. Kubernetes actually handles this. I'd even go as far as to say it's one of its most important features. Kubernetes is an abstraction over your physical hardware in that it makes all your computing resources look like one bundle of resources. It intelligently schedules apps, workers, databases, etc to run on whatever node (i.e. server) currently has capacity. If you run out of resources, just add another node. Kubernetes will happily start scheduling stuff to run on it. In other words, you don't have to care which node your app runs on. Redis, Postgres, your Rails app, etc are only set up once. Kubernetes also handles all the networking so the "pods" (i.e. running things) can talk to each other, even if they reside on different physical nodes. If you want to run more than one instance of your app, you'd bump up the number of replicas, eg:

```ruby
Kuby.define('MyApp') do
  environment(:production) do
    kubernetes do
      add_plugin(:rails_app) do
        replicas 2
      end
    end
  end
end
```

Kuby deploys a "Service" load balancer that will send traffic evenly between the two pods/instances. Again, this works even if the pods are running on different physical nodes.

**NOTE**: Unless you've got some intelligent sharding or replication set up, databases like Redis and Postgres should always run on a single node, i.e. shouldn't be balanced between multiple nodes.

This begs the question: how do you get things to run on different nodes to mitigate failure? Kubernetes has the concept of pod "affinity" and "anti-affinity" that Kuby supports but doesn't expose in a turnkey way. Let me know if you're interested in that and I can point you to some resources.

Lastly, the assets issue you mentioned is unfortunately a bug I/we need to fix. You _should_ be able to run your Kuby-deployed app across any number of nodes.

**Comment by brandoncc** [comment]
@camertron if my jaw could have literally hit the floor just now, it would have. That is both awesome and scary at the same time.

Thank you for this information, I really appreciate it.
