### ISSUE TITLE
Wait for database to start

### ISSUE THREAD

**Issue by camertron** [getkuby/kuby-core#47]
Often the very first Kuby deploy will fail because the database hasn't started yet. We should be able to add a mechanism to Kuby to wait for the db to respond before starting web pods.

**Comment by severinraez** [comment]
Maybe our gem [bleib](https://github.com/puzzle/bleib) can help here!

**Comment by camertron** [comment]
Thanks for the tip @severinraez, bleib looks cool! I'm curious about the name - is there a story there?

**Comment by severinraez** [comment]
No worries, glad to help (if it helps 😊)!

Regarding the name:. "Bleib" is the german version of the command "stay"
used to tell dogs to wait. It does just that, but with your rails app...

Cameron Dutro <notifications@github.com> schrieb am Di., 22. Dez. 2020,
20:13:

**Comment by camertron** [comment]
@severinraez love it, very clever!

**Comment by camertron** [comment]
With the recent migration to CockroachDB I changed the way Kuby checks for a running database server, and deploys are now quite smooth :)
