### ISSUE TITLE
Does not login to docker registry

### ISSUE THREAD

**Issue by traels** [getkuby/kuby-core#5]
Either there should be a not about logging in to a registry before pushing image - or it should login with the credentials given in config file.

**Comment by camertron** [comment]
Oh yeah, good call. This is something the lib can do for you, although it's probably worth adding something to the documentation as well. I'll look into adding both.

**Comment by camertron** [comment]
I ended up adding this in code, which means it's really not necessary to mention in the docs. Published in v0.7.0.
