### ISSUE TITLE
Kuby::Docker::MissingTagError

### ISSUE THREAD

**Issue by traels** [getkuby/kuby-core#7]
The tags still will not work. Running deploy (v. **0.7.0**) I get this:

** Invoke kuby:deploy (first_time)
** Execute kuby:deploy
rake aborted!
Kuby::Docker::MissingTagError: Could not find tag 'could not find latest timestamped tag'.

I've done some spelunking and had kuby print out the list of tags: ["20200811075435", "latest", "20200810165134"]

**Comment by camertron** [comment]
Ugh I see the problem. Let's get rid of this crazy regex.

**Comment by camertron** [comment]
Should be fixed (🤞) as of v0.7.1.
