### ISSUE TITLE
master.key can be compromised in Docker image

### ISSUE THREAD

**Issue by kingdonb** [getkuby/kuby-core#75]
I don't know if I followed the instructions to the letter, but I have a test repo that I have used from `rails new` and it has a `config/master.key` in the working directory (in the usual spot), which was quite unceremoniously built into the docker image and pushed up to the hub.

This is especially dangerous because docker hub credentials are embedded according to the instructions, so compromise of the master.key probably means compromising the image host and/or cloud platform keys (!!!)

I'm not sure if kuby generated my .dockerignore but I feel like `config/master.key` should definitely be listed in there as well, for a first step. Maybe there should be more involved process for ensuring that master keys don't get baked into images but I'm fairly certain that this one enhancement would have stopped me from compromising mine 👍

**Comment by camertron** [comment]
Hey @kingdonb that's interesting! I thought `docker build` used .gitignore as well as .dockerignore, but I guess not! Definitely a big problem, thanks for reporting.

**Comment by camertron** [comment]
I just went back into the rails generator code. I had totally forgotten that Kuby generates a .dockerignore... but doesn't ignore config/master.key! Oops 😳

Fixed in [this commit](https://github.com/getkuby/kuby-core/commit/13786d82d0d9b68e14eee210c616a5b1a0241408).

**Comment by kingdonb** [comment]
Hooray! Thank you!
