### ISSUE TITLE
RailsConf interest?

### ISSUE THREAD

**Issue by yebyen** [getkuby/kuby-core#89]
Any interest in presenting Kuby for RailsConf?

![Screenshot_20220204-063445](https://user-images.githubusercontent.com/1025518/152522736-75ebd2a1-c3c3-4cfb-8cd2-3901124618e2.png)

I'm thinking about submitting something about Kuby and GitOps for the CFP that's open now!

**Comment by camertron** [comment]
Hey @yebyen! Yeah, I've submitted Kuby talks to RailsConf and RubyConf and been denied both times 😢 I'm planning on submitting again this time around for RailsConf, but I think you should submit your talk too. There might be more interest in a GitOps-flavored talk than there would be for the one I'm planning to submit. In the end, more exposure can only be a good thing for the Kuby project, so go for it!

**Comment by kingdonb** [comment]
I have a CFP that is in the queue, it mentions Kuby prominently. I'd like to send it to you for your interest and share. The CFP is blind and I don't want to share it publicly, as the submission period is still open. Can I send it to you via e-mail as PDF?

**Comment by camertron** [comment]
@kingdonb  just emailed you!
