### ISSUE TITLE
Skip assets compilation

### ISSUE THREAD

**Issue by denikus** [getkuby/kuby-core#95]
Is there any legal way to skip assets compilation and copying (and also asset resource running at all)?

I have api-only app, so there's no even assets:precompile task available.

So, my deployment stops at the moment:
```
Continuing to wait for: Deployment/xxxxxx-assets
Still waiting for: Deployment/xxxxxx-assets
Still waiting for: Deployment/xxxxxx-assets
```

**Comment by camertron** [comment]
Hey @denikus, thanks for bringing this up. Asset compilation is done via a plugin, but there's no official way to remove plugins at the moment. That being said, you should be able to do this in your Kuby config:

```ruby
Kuby.define('App') do
  environment(:production) do
    docker do
      delete :assets_phase
    end
  end
end

Kuby.environment.kubernetes do
  @plugins.delete(:rails_assets)
end
```
