### ISSUE TITLE
Upgrade Krane dependency

### ISSUE THREAD

**Issue by cyu** [getkuby/kuby-core#99]
Running into an issue where I cannot bundle install because I can't resolve a dependency:

```
Bundler could not find compatible versions for gem "http":
  In snapshot (Gemfile.lock):
    http (>= 5.0.1)

  In Gemfile:
    kuby-core (= 0.17.0) was resolved to 0.17.0, which depends on
      krane (< 2.0, >= 1.1.4) was resolved to 1.1.4, which depends on
        kubeclient (~> 4.3) was resolved to 4.4.0, which depends on
          http (~> 3.0)

    noticed (~> 1.3) was resolved to 1.5.9, which depends on
      http (>= 4.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by camertron** [comment]
Hey @cyu, thanks for letting me know about this. Looks like it should just be a matter of upgrading Krane, since later versions support http < 5.

**Comment by cyu** [comment]
@camertron is there some known issue that would make this difficult, or is it possible that it will work with potentially small effort?  Trying to gauge if it is worthwhile to attempt this myself and submit a PR.

**Comment by camertron** [comment]
There's a good chance it'll be pretty easy, although from what I understand not too many people use Krane as a library. If any changes are necessary to Kuby, they'll be localized to [this file](https://github.com/getkuby/kuby-core/blob/master/lib/kuby/kubernetes/deploy_task.rb).

**Comment by camertron** [comment]
I just took a quick look at Krane's [CHANGELOG entry for v2.0](https://github.com/Shopify/krane/blob/master/CHANGELOG.md#200). It looks like the only breaking change was renaming an annotation namespace, which shouldn't affect Kuby at all.

**Comment by camertron** [comment]
Hey @cyu, I went ahead and upgraded Krane in the master branch in preparation for a big release ahead of RailsConf. It turned out to be a matter of simply bumping the gem in the gemspec 😄
